site_name: mkdocs-template
site_url: https://gjcav.github.io/mkdocs-template/
repo_url: https://github.com/GJCav/mkdocs-template

theme: 
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - content.code.annotate 

plugins:
- awesome-pages
- tags:
    tags_file: tag-index.md
- search:
    lang:  [ en, ja ]

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true 
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
