name: ci 
on:
  push:
    branches:
      - master 
      - main
  workflow_dispatch:

permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: |
          echo debug info
          python3 --version
          which pip
          ls -lha
          ls -lha mkdocs-material
          echo "G_PROPERTY: $G_PROPERTY"
        env:
          G_PROPERTY: ${{ vars.G_PROPERTY }}
      - run: bash install.sh
      - run: mkdocs gh-deploy --force
        env:
          G_PROPERTY: ${{ vars.G_PROPERTY }}
